server:
  port: 9091

spring:
  application:
  name: kafka-producer
  kafka:
    producer:
      bootstrap-servers: localhost:9092
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

      acks: all
      retries: 10
      properties:
        retry:
          backoff:
            ms: 1000
        delivery:
          timeout:
            ms: 120000
        linger:
          ms: 0
        request:
          timeout:
            ms: 3000
        enable:
          idempotence: true
